# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-30 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('scontend', models.CharField(max_length=20)),
                ('sclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.OneClass')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('tcontend', models.CharField(max_length=20)),
                ('tclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.OneClass')),
            ],
        ),
    ]
